{% set version = "1.6.4" %}

package:
  name: windrose
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/windrose/windrose-{{ version }}.tar.gz
  sha256: 540b3dcb8a0cb62e549e1e82019e591c30f04e9794b21a5a456f1c9adff433cb

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib
    - numpy

test:
  imports:
    - windrose

about:
  home: https://github.com/python-windrose/windrose
  license: BSD-3-Clause
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENCE_BSD-3-Clause.TXT'
  summary: 'Python Matplotlib, Numpy library to manage wind data, draw windrose.'

extra:
  recipe-maintainers:
    - ocefpaf
