{% set version = "1.8.1" %}

package:
  name: windrose
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/windrose/windrose-{{ version }}.tar.gz
  sha256: 2b03ebb5f98234a524313d8a729b503d0825ac5ed507fef66af793d31798064c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - pandas
    - scipy

test:
  imports:
    - windrose

about:
  home: https://github.com/python-windrose/windrose
  license: BSD-3-Clause
  license_file: LICENCE_BSD-3-Clause.txt
  summary: Python Matplotlib, Numpy library to manage wind data, draw windrose.

extra:
  recipe-maintainers:
    - ocefpaf
