{% set name = "windrose" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/windrose-{{ version }}.tar.gz
  sha256: 0f0fad74e88116bc5b93ac610ee5d2515852528de2bc941e7c121a7226d93e6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3
    - numpy >=1.21

test:
  imports:
    - windrose
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-windrose/windrose
  summary: Python Matplotlib, Numpy library to manage wind data, draw windrose (also known as a polar rose plot)
  license: BSD-3-Clause
  license_file: LICENCE_BSD-3-Clause.txt

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
