{% set name = "windrose" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/windrose-{{ version }}.tar.gz
  sha256: 70200afe01721bfe4a10ea26cbcc3e5c23800566921bbb8a34b0f68ade488bfa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3
    - numpy >=1.21

test:
  imports:
    - windrose
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python-windrose/windrose
  summary: Python Matplotlib, Numpy library to manage wind data, draw windrose (also known as a polar rose plot)
  license: BSD-3-Clause
  license_file: LICENCE_BSD-3-Clause.txt

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
