{% set version = "1.6" %}

package:
  name: windrose
  version: {{ version }}

source:
  fn: windrose-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/w/windrose/windrose-{{ version }}.tar.gz
  sha256: cbeb0f178944f1838bc84e87bac177e6a8d98478703f559528f5d72aa1e888fa
  patches:
    - setup-patch.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - numpy

test:
  imports:
    - windrose

about:
  home: https://github.com/scls19fr/windrose
  license: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)
  summary: 'Python Matplotlib, Numpy library to manage wind data, draw windrose.'

extra:
  recipe-maintainers:
    - ocefpaf
