travis:
  secure:
    BINSTAR_TOKEN: QTPAEZCc1fh8BMC9tr4p4OxTEEhJ39UBdoCMK/F4tNevm3p8xumPlw8nZSVue2aAzJnPyYksYKuRhagWiMFF6CsiThNJOfZaIXuqXwSHI3TqkS2+oLvy8FHhm2M4N8PBeZri9gRbanD9/hIaFULYkaY4+19t92ghwNVdpJSansEUQRdWKMgNaMQittE+YJXckSKpmQPYDTWx/if8Ox7Xc0YuaHaNrOCkAuZqaW0ik+wGH6BFu+TQ2lVLTj8AgaZLteAL7esP4498thQaLc/ieedmqOQt5sQdcLzNbrnBoQY5rpHpAWsOldwPLxgZHhE9l06GC34qwZKAo+SE8gsGsgWdgDzepzGuUhNqEOWTIl3KHNOV6L23gejUpq7MtbT4tN9g8hVlpViklehNKdI40yIsBhyfr8e9cyD0WWMDVZMc6fg+Ua+k6fRTP5ETHQX+K9mFRDlS/YsKsxOUPE6UdXLOVlQj4D5XeexH8p3WCa4ji1KrHFDUPnOh0EhtlI2Q9gfB2NYlpkrwt4YV7dfOdDKWAhcUJzZkzj2bd+rd02BtFzQGZHlYwzhAbQz8yFDCZolBaRM/0DDab8ePOM76jruPXK6isq42Vs7qTKJdVMmCs9NXdsZ8M2lpKnPta8bVd+g8q01/PMNEpH9zKmWrauTmAp78rwnVL9wzdXSGjyo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
