travis:
  secure:
    BINSTAR_TOKEN: MRc2CFiQugb1g/Xw/+EXl3Kq+ae+wfwtAJtntS/lLCpV2qvrGeZyW2j1tQx0mQ+TdHksLfaGhsiN0GHqjPG3hfIJHw4iFYZZbcKoCPXrIqHPNFxLubOMPoVqDtR6b443/Q3UrgRAyiDwFj3lRG8WTH9QLZjTjAzFXuUmFhp3mGqqHFF0xgV8FQz1pG4mT/Qu6WppMqbZoCcTd5txIfbZK8QTne93fR67f7mEwkM+W//Eo5afavcqqPYEcVs13ruCHbfvo1bzFRycrDZUbMtCUzptriv4Jk6lC5wAtzfbaYTNUzH+cVmVJHvIdTA3/+BcFycs4OS8ceX+NqoSzLqyQXU1jGjomE519X7oxLFnt0aDH3N3w6lmEp4GONLvaYgtdxgegaaxrHKR7pktPmE3WpU/CD0sxjQzeS8rIP83hx5GIyTNhjF9Z0yg46o64sDeCLcLPWIT3P6Wb2uWVxHjtLrWZFAlRKhmfvA5HJ+NkYR6FgRYnAjS+RkN4ByxCLXliapq4yKp2383/jFNz4veHJ+MCiOsZu54Ra/CrrU4KjCpuWDom/cx45CN8eTEvcN+W8KKEvavD7gd8o4xo2o3SF5YXgFJ3nxMjMwUtVxrt03vkomNi9h+7sh2FfYc5jhRqgKxfZ0nezwR5ysWlc/BGxR8dznc7TkcmBPHiUyO5kk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
